#### Importing Library

In [ ]:
import numpy as np

#### Creating an array using "np.array()"

In [ ]:
# 1-D Array
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Dimensions: 1


In [ ]:
# 2-D Array with one row
arr2 = np.array([[1,2,3,4,5,6,7,8,9,10]])
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)

[[ 1  2  3  4  5  6  7  8  9 10]]
Shape: (1, 10)
Dimensions: 2


*   *Here we can see shape is (1,10) which means 2-D Array with 1 Rows and 10 Columns*

In [ ]:
# 2-D Array with more than one row
arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr3)
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Dimensions: 2


*   *Here we can see shape is (2,5) which means 2-D Array with 2 Rows and 5 Columns*

In [ ]:
# 2-D Array with more than two rows
arr4 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arr4)
print("Shape:", arr4.shape)
print("Dimensions:", arr4.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Shape: (3, 5)
Dimensions: 2


*   *Here we can see shape is (3,5) which means 2-D Array with 3 Rows and 5 Columns*

In [ ]:
# 3-D Array with 2 blocks(3rd Dimensions)
arr5 = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]]])
print(arr5)
print("Shape:", arr5.shape)
print("Dimensions:", arr5.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
Shape: (2, 2, 5)
Dimensions: 3


*   *Here we can see shape is (2,2,5) which means 3-D Array with 2 blocks of (2,5) shape arrays*

In [ ]:
# 3-D Array with 3 blocks(3rd Dimensions)
arr6 = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]],[[21,22,23,24,25], [26,27,28,29,30]]])
print(arr6)
print("Shape:", arr6.shape)
print("Dimensions:", arr6.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
Shape: (3, 2, 5)
Dimensions: 3


*   *Here we can see shape is (3,2,5) which means 3-D Array with 3 blocks of (2,5) shape arrays*

In [ ]:
# 4-D Array
arr7 = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]],[[21,22,23,24,25], [26,27,28,29,30]]],
                 [[[1,2,3,4,5], [6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]],[[21,22,23,24,25], [26,27,28,29,30]]]])
print(arr7)
print("Shape:", arr7.shape)
print("Dimensions:", arr7.ndim)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]

  [[11 12 13 14 15]
   [16 17 18 19 20]]

  [[21 22 23 24 25]
   [26 27 28 29 30]]]


 [[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]

  [[11 12 13 14 15]
   [16 17 18 19 20]]

  [[21 22 23 24 25]
   [26 27 28 29 30]]]]
Shape: (2, 3, 2, 5)
Dimensions: 4


*   *Here we can see shape is (2,3,2,5) which means 4-D Array with 2 blocks of (3,2,5) shape arrays*

---





**size:**
*  size attribute gives us total number of elements in an array
*  it can also be calculated by multiplying each all numbers in shape
*  for example if the shape is (2,3,2,5)
*  size = 2 x 3 x 2 x 5 = 60

In [ ]:
# 4-D Array
arr7 = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]],[[21,22,23,24,25], [26,27,28,29,30]]],
                 [[[1,2,3,4,5], [6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]],[[21,22,23,24,25], [26,27,28,29,30]]]])
print(arr7)
print("Shape:", arr7.shape)
print("Dimensions:", arr7.ndim)
print("Size:", arr7.size)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]

  [[11 12 13 14 15]
   [16 17 18 19 20]]

  [[21 22 23 24 25]
   [26 27 28 29 30]]]


 [[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]

  [[11 12 13 14 15]
   [16 17 18 19 20]]

  [[21 22 23 24 25]
   [26 27 28 29 30]]]]
Shape: (2, 3, 2, 5)
Dimensions: 4
Size: 60




---





**itemsize:**
*  itemsize gives us length of one array element in bytes

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = "int")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Itemsize:", arr1.itemsize)

[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Dimensions: 1
Itemsize: 8


In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = "float")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Itemsize:", arr1.itemsize)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Shape: (10,)
Dimensions: 1
Itemsize: 8


In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = "complex")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Itemsize:", arr1.itemsize)

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]
Shape: (10,)
Dimensions: 1
Itemsize: 16




*   if data type of array elements is integer, itemsize = 8
*   if data type of array elements is float, itemsize = 8
*   if data type of array elements is complex, itemsize = 16 



**.dtype:**


*   it gives the data type of array elements.



In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = "int")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Dimensions: 1
Data Type: int64


In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = "float")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Shape: (10,)
Dimensions: 1
Data Type: float64


In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = "complex")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]
Shape: (10,)
Dimensions: 1
Data Type: complex128


#### Creating an array using "np.ones()"

In [ ]:
# 1-D Array with 10 elements
arr1 = np.ones(10)
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Shape: (10,)
Dimensions: 1
Data Type: float64


*Here the default datatype of .ones() is float. we can change it if we want, follow the next step*

In [ ]:
# 1-D Array with 10 elements with integer datatype
arr1 = np.ones(10, dtype="int")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)

[1 1 1 1 1 1 1 1 1 1]
Shape: (10,)
Dimensions: 1
Data Type: int64


In [ ]:
# 2-D Array
arr2 = np.ones((4,5))
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (4, 5)
Dimensions: 2
Data Type: float64


inside np.ones() we need to give the shape of an array that we want to create.

In [ ]:
# 3-D Array
arr3 = np.ones((4,4,5))
print(arr3)
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)
print("Data Type:", arr3.dtype)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
Shape: (4, 4, 5)
Dimensions: 3
Data Type: float64


In [ ]:
# 4-D Array
arr4 = np.ones((5,3,2,5))
print(arr4)
print("Shape:", arr4.shape)
print("Dimensions:", arr4.ndim)
print("Data Type:", arr4.dtype)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
Shape: (5, 3, 2, 5)
Dimensions: 4
Data Type: float64


In [ ]:
# 5-D Array
arr5 = np.ones((3,2,3,2,3))
print(arr5)
print("Shape:", arr5.shape)
print("Dimensions:", arr5.ndim)
print("Data Type:", arr5.dtype)

[[[[[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]]


  [[[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]]]



 [[[[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]]


  [[[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]]]



 [[[[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]]


  [[[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]]]]]
Shape: (3, 2, 3, 2, 3)
Dimensions: 5
Data Type: float64


#### Creating an array using "np.zeros()"

In [ ]:
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


np.zeroes() is same as np.ones() only difference is np.zeroes() generates zeroes and np.ones() generates ones

#### Creating an Array using np.eye()


*   np.eye() produces an identity matrix
*   if we give only one argument in eye() then it produces square matrix
*   for example, if we give like np.eye(5) then it produces identity matrix with shape of (5,5)
*   if we give like np.eye(4,5) then it produces an identity matrix with shape of (4,5) i.e 4 rows and 5 columns


In [ ]:
arr1 = np.eye(5)
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape: (5, 5)
Dimensions: 2


In [ ]:
arr2 = np.eye(4,5)
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
Shape: (4, 5)
Dimensions: 2


Note: we can only create 2-D array with np.eye()

In [ ]:
arr3 = np.eye(5, k=1)
print(arr3)
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
Shape: (5, 5)
Dimensions: 2


*   *if we give k=1 it shifts all the ones 1 row up.*
*   *if we give k=2 it shifts all the ones 2 rows up. and so on for k = 3,4,5......*

In [ ]:
arr4 = np.eye(5, k=2)
print(arr4)
print("Shape:", arr4.shape)
print("Dimensions:", arr4.ndim)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Shape: (5, 5)
Dimensions: 2


In [ ]:
arr5 = np.eye(5, k=-1)
print(arr5)
print("Shape:", arr5.shape)
print("Dimensions:", arr5.ndim)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
Shape: (5, 5)
Dimensions: 2


*   *if we give k=-1 it shifts all the ones 1 row up.*
*   *if we give k=-2 it shifts all the ones 2 rows up. and so on for k = -3,-4,-5......*

In [ ]:
arr6 = np.eye(5, k=-2)
print(arr6)
print("Shape:", arr6.shape)
print("Dimensions:", arr6.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
Shape: (5, 5)
Dimensions: 2


**Note:** *By default k = 0*

#### Creating an array using np.identity()


*   np.identity() takes one argument
*   if we give like np.identity(4) then if creates and identity matrix with shape(4,4)



In [ ]:
arr1 = np.identity(4)
print(arr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Note:** difference between eye() and identity()
*   identity() creates only square matrix where as eye() can create identity matrix with any shape
*   there is no 'k' attribute in identity() unlike eye()

In [ ]:
arr2 = np.identity(3, dtype = "int")
print(arr2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Creating an array with np.full()
*   np.full() creates and array with a given shape and we can give a number that we want to fill the array with.
*   if takes two arguments shape and a number to fill array with
*   for example, if we give like np.full((3,4),6), it creates an array with shape (3,4) and with all elements as 6 in it.

In [ ]:
# 1-D Array
arr1 = np.full((10,), 6)
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)

[6 6 6 6 6 6 6 6 6 6]
Shape: (10,)
Dimensions: 1


In [ ]:
# 2-D Array
arr2 = np.full((5,4), 2)
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
Shape: (5, 4)
Dimensions: 2


In [ ]:
# 3-D Array
arr3 = np.full((4,2,4), 4)
print(arr3)
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)

[[[4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]]]
Shape: (4, 2, 4)
Dimensions: 3


In [ ]:
# 4-D Array
arr4 = np.full((3,4,2,4), 4)
print(arr4)
print("Shape:", arr4.shape)
print("Dimensions:", arr4.ndim)

[[[[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]]


 [[[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]]


 [[[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]

  [[4 4 4 4]
   [4 4 4 4]]]]
Shape: (3, 4, 2, 4)
Dimensions: 4


#### Creating an array with np.arange()

In [ ]:
arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr2 = np.arange(50,70)
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [ ]:
arr3 = np.arange(20,50,3)
print(arr3)

[20 23 26 29 32 35 38 41 44 47]


In [ ]:
arr4 = np.arange(-20,-1, 1)
print(arr4)

[-20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3
  -2]


In [ ]:
arr5 = np.arange(20, 1, -1)
print(arr5)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]


Note: 
*   We can only create 1-D Array with np.arange()
*   We can also give step as float in arange()

In [ ]:
arr6 = np.arange(1,10, 0.5)
arr6

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
arr7 = np.arange(0.5, 10, 0.25)
arr7

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75,
       6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 ,
       8.75, 9.  , 9.25, 9.5 , 9.75])

In [ ]:
arr7 = np.arange(0.5, 9.25, 0.25)
arr7

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75,
       6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 ,
       8.75, 9.  ])

#### Creating an Array with np.linspace()

In [ ]:
arr1 = np.linspace(1,10)
print(arr1)
print("------------------------------------")
print("Size:", arr1.size)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
------------------------------------
Size: 50


In [ ]:
arr2 = np.linspace(1,20,num = 10)
print(arr2)
print("------------------------------------")
print("Size:", arr2.size)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]
------------------------------------
Size: 10


In [ ]:
arr2 = np.linspace(1,10,num = 10, retstep=True)
print(arr2)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


In [ ]:
arr2 = np.linspace(1,19,num = 10, retstep=True)
print(arr2)

(array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.]), 2.0)


In [ ]:
arr2 = np.linspace(0,20,num = 11, retstep = True)
print(arr2)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), 2.0)


In [ ]:
arr2 = np.linspace(start=0, stop=20, num=11, retstep=True)
print(arr2)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), 2.0)


np.linspace() works on the principle of Arithmatic Progression
*   **a + (n-1)d = l**
*   compare with **start + (num-1) x retstep = stop**

In [ ]:
arr2 = np.linspace(start=0.5, stop=2.3, num=11, retstep=True)
print(arr2)

(array([0.5 , 0.68, 0.86, 1.04, 1.22, 1.4 , 1.58, 1.76, 1.94, 2.12, 2.3 ]), 0.18)


#### Creating an Array with np.random.rand()


1.   rand() returns an array with random numbers less than 1 with a given shape
2.   randn() returns an array with random numbers which are both positive and negative with a given shape



In [ ]:
arr1 = np.random.rand(3)
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)

[0.74439276 0.7985642  0.88598418]
Shape: (3,)
Dimensions: 1


In [ ]:
arr2= np.random.rand(3,2)
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)

[[0.3591938  0.59702096]
 [0.42186852 0.67580996]
 [0.32101468 0.52863639]]
Shape: (3, 2)
Dimensions: 2


In [ ]:
arr3 = np.random.rand(4,3,5)
print(arr3)
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)

[[[0.63903141 0.88193967 0.6426634  0.45894904 0.68503996]
  [0.84205936 0.45412548 0.77514565 0.93462604 0.40690305]
  [0.02459774 0.01394284 0.50146462 0.46058075 0.44695663]]

 [[0.23630714 0.65901045 0.72521673 0.3172857  0.18400302]
  [0.99450176 0.56872321 0.22439213 0.222066   0.4042872 ]
  [0.21229145 0.82583105 0.92972669 0.08241002 0.83971397]]

 [[0.26517483 0.58742876 0.16018487 0.89557521 0.07834965]
  [0.66459282 0.29084688 0.5352894  0.38465239 0.3425014 ]
  [0.5455989  0.73061251 0.31685854 0.52979612 0.23681392]]

 [[0.7997342  0.60466125 0.34826229 0.6665379  0.86051909]
  [0.41237553 0.90425667 0.11121675 0.82284396 0.25203679]
  [0.7373598  0.81239811 0.09605235 0.88074282 0.75449886]]]
Shape: (4, 3, 5)
Dimensions: 3


#### Creating an Array with np.random.randint()
*   it takes three arguments low, high, shape
*   it returns an array with the given shape and numbers between low(included) and high(excluded)

In [ ]:
arr1 = np.random.randint(10,20,(3,4,5))
print(arr1)
print("Shape:", arr1.shape)

[[[13 15 16 16 10]
  [13 16 16 15 17]
  [19 19 13 12 18]
  [14 19 14 10 19]]

 [[10 13 18 12 12]
  [16 11 15 17 12]
  [17 19 16 14 10]
  [14 13 10 17 19]]

 [[10 18 13 11 19]
  [13 13 12 17 19]
  [11 14 13 11 14]
  [15 18 10 17 19]]]
Shape: (3, 4, 5)


In [ ]:
arr1 = np.random.randint(0,20,(2,4,4,5))
print(arr1)
print("Shape:", arr1.shape)

[[[[18 12  4 16 11]
   [15  6 19  1 12]
   [11  0  9 18  7]
   [ 4  5 10 13  5]]

  [[10 13  8 13  6]
   [ 1  3 19 14  8]
   [ 8  4  0 13  2]
   [13  1 17 16 13]]

  [[14  3  3 19  0]
   [11  5 14 18 15]
   [ 3 13  0  2  4]
   [ 1  3 15 14  6]]

  [[11 16  7  3  7]
   [18 18 17 10 11]
   [10  5  5 14  0]
   [18 12  5 10 14]]]


 [[[ 3  4 10 11 18]
   [10  8 13 13 13]
   [17  4 18  6  1]
   [10 15  0  9  9]]

  [[13 12  2 12  3]
   [11 15 10 12 19]
   [12  5 14 19 11]
   [12 18  0  4 17]]

  [[ 6  4  2  2  3]
   [ 0 18 16  4  4]
   [ 6 12 17  0  3]
   [19  5  3  9  2]]

  [[19  5 18 16  4]
   [ 9 13  5  9  9]
   [ 0  2 14  6 15]
   [15  8 14  2 14]]]]
Shape: (2, 4, 4, 5)


#### Creating an Array with np.random.choice()

In [ ]:
arr1 = np.arange(10,15)
print(arr1)

[10 11 12 13 14]


In [ ]:
arr2 = np.random.choice(arr1, size = (4,5), p = [0.3,0.1,0.2,0.1,0.3])
print(arr2)

[[12 12 12 13 14]
 [14 11 12 14 14]
 [12 12 12 14 11]
 [12 12 10 14 14]]


In [ ]:
arr2 = np.random.choice(arr1, size = (3,4,5), p = [0.3,0.1,0.2,0.1,0.3])
print(arr2)

[[[12 12 12 10 10]
  [14 14 10 10 10]
  [10 11 14 10 14]
  [14 12 10 13 11]]

 [[10 10 14 14 13]
  [10 10 10 12 14]
  [11 14 14 10 11]
  [14 11 11 13 10]]

 [[14 10 11 13 10]
  [10 10 14 14 12]
  [10 10 14 10 10]
  [14 14 14 12 12]]]


In [ ]:
arr2 = np.random.choice(arr1, size = (3,2,4,5), p = [0.3,0.1,0.2,0.1,0.3])
print(arr2)

[[[[10 12 11 10 12]
   [14 11 14 14 13]
   [14 10 13 10 12]
   [14 11 12 10 12]]

  [[13 14 12 10 14]
   [10 14 10 11 14]
   [14 14 12 11 10]
   [14 13 14 12 14]]]


 [[[10 12 10 13 11]
   [12 12 14 10 13]
   [13 10 14 14 11]
   [14 10 14 14 10]]

  [[10 10 10 14 10]
   [10 12 10 14 10]
   [12 14 14 12 10]
   [10 14 10 10 10]]]


 [[[11 12 11 12 11]
   [14 14 14 11 14]
   [14 10 12 14 10]
   [10 10 14 12 11]]

  [[10 14 11 14 10]
   [10 13 14 10 14]
   [11 12 13 14 14]
   [10 13 12 10 14]]]]


**Note:** *choice() takes only 1-D Array as input*